import type { Grant, GrantCategory } from "@/lib/types";
import { useMemo } from "react";

  // Sample grants data
  export const useGrantsData = () => {
  const grants: Grant[] = useMemo(
    () => [
      {
        id: '1',
        title: 'Tony Elumelu Foundation Entrepreneurship Programme',
        organization: 'Tony Elumelu Foundation',
        amount: '$5,000',
        category: 'Business',
        deadline: 'Dec 31, 2026',
        status: 'open',
        description: 'The TEF Entrepreneurship Programme is open to entrepreneurs from all 54 African countries. The Programme provides training, mentoring, and seed capital funding of $5,000 to African entrepreneurs.',
        requirements: [
          'Must be between 18-35 years old',
          'Business must be less than 3 years old',
          'Must be an African citizen',
          'Must have a viable business plan',
        ],
        eligibility: [
          'African entrepreneurs',
          'Business owners',
          'Startups and MSMEs',
          'All sectors welcome',
        ],
        applicationLink: 'https://tefconnect.com',
      },
      {
        id: '2',
        title: 'YouWiN! Connect Program',
        organization: 'Federal Government of Nigeria',
        amount: '₦1,000,000 - ₦10,000,000',
        category: 'Business',
        deadline: 'Nov 30, 2026',
        status: 'closing-soon',
        description: 'Youth Enterprise With Innovation in Nigeria (YouWiN!) Connect is designed to encourage and support aspiring and early-stage entrepreneurs to develop and execute business ideas that will generate employment.',
        requirements: [
          'Nigerian citizen between 18-45 years',
          'Must have NIN',
          'Business plan required',
          'Must create employment opportunities',
        ],
        eligibility: [
          'Nigerian youth entrepreneurs',
          'First-time applicants',
          'Innovative business ideas',
          'Job creation focus',
        ],
        applicationLink: null,
      },
      {
        id: '3',
        title: 'Google for Startups Black Founders Fund',
        organization: 'Google',
        amount: '$100,000',
        category: 'Technology',
        deadline: 'Jan 15, 2025',
        status: 'open',
        description: 'Non-dilutive cash awards and hands-on support for Black-led startups building technology companies across Africa.',
        requirements: [
          'Black-founded startup',
          'Technology-focused company',
          'Registered business entity',
          'At least $500K in revenue or funding',
        ],
        eligibility: [
          'African startups',
          'Black founders',
          'Tech companies',
          'Growth stage',
        ],
        applicationLink: null,
      },
      {
        id: '4',
        title: 'Mastercard Foundation Scholars Program',
        organization: 'Mastercard Foundation',
        amount: 'Full Scholarship',
        category: 'Education',
        deadline: 'Feb 28, 2025',
        status: 'open',
        description: 'The Mastercard Foundation Scholars Program provides academically talented yet economically disadvantaged young people with the opportunity to complete their education.',
        requirements: [
          'Academic excellence',
          'Financial need',
          'Leadership potential',
          'Commitment to giving back',
        ],
        eligibility: [
          'African students',
          'Undergraduate/Graduate',
          'Age 18-30',
          'Strong academic record',
        ],
        applicationLink: null,
      },
      {
        id: '5',
        title: 'CBN Youth Entrepreneurship Development Programme',
        organization: 'Central Bank of Nigeria',
        amount: '₦250,000 - ₦3,000,000',
        category: 'Agriculture',
        deadline: 'Dec 15, 2026',
        status: 'open',
        description: 'YEDP aims to address youth unemployment by providing financial assistance and business training to young Nigerians in agriculture and agro-processing.',
        requirements: [
          'Age 18-35 years',
          'Nigerian citizen',
          'Valid BVN',
          'Agriculture/agro-processing focus',
        ],
        eligibility: [
          'Youth entrepreneurs',
          'Agriculture sector',
          'Nigerian nationals',
          'Business plan required',
        ],
        applicationLink: null,
      },
      {
        id: '6',
        title: 'She Leads Africa Accelerator',
        organization: 'She Leads Africa',
        amount: '$10,000',
        category: 'Women',
        deadline: 'Jan 31, 2025',
        status: 'open',
        description: 'Supporting women-led businesses across Africa with funding, mentorship, and access to networks.',
        requirements: [
          'Woman founder/co-founder',
          'Business operational for 1+ year',
          'Revenue generating',
          'Based in Africa',
        ],
        eligibility: [
          'Women entrepreneurs',
          'African-based businesses',
          'All sectors',
          'Growth-stage companies',
        ],
        applicationLink: null,
      },
      {
        id: '7',
        title: 'AfDB Youth Entrepreneurship and Innovation Multi-Donor Trust Fund',
        organization: 'African Development Bank',
        amount: '$50,000 - $150,000',
        category: 'Innovation',
        deadline: 'Nov 20, 2026',
        status: 'closing-soon',
        description: 'Supports innovative youth-led enterprises that can scale and create jobs across Africa.',
        requirements: [
          'Youth-led enterprise (founder <35)',
          'Innovative business model',
          'Scalability potential',
          'Job creation focus',
        ],
        eligibility: [
          'African youth',
          'Innovative startups',
          'All sectors',
          'Early to growth stage',
        ],
        applicationLink: null,
      },
      {
        id: '8',
        title: 'UNICEF Innovation Fund',
        organization: 'UNICEF',
        amount: '$100,000',
        category: 'Social Impact',
        deadline: 'Rolling',
        status: 'open',
        description: 'Invests in early-stage open-source technology solutions that have the potential to positively impact children and young people.',
        requirements: [
          'Open-source technology',
          'Prototype developed',
          'Team of 2-7 people',
          'Focus on children/youth impact',
        ],
        eligibility: [
          'Tech startups',
          'Social impact focus',
          'Developing countries',
          'Open-source commitment',
        ],
        applicationLink: null,
      },
    ],
    []
  );

  const categories: GrantCategory[] = useMemo(
    () => [
      { id: 'all', name: 'All Grants', icon: 'apps', color: '#3b82f6', count: grants.length },
      {
        id: 'business',
        name: 'Business',
        icon: 'briefcase',
        color: '#8b5cf6',
        count: grants.filter((g) => g.category === 'Business').length,
      },
      {
        id: 'technology',
        name: 'Technology',
        icon: 'laptop',
        color: '#06b6d4',
        count: grants.filter((g) => g.category === 'Technology').length,
      },
      {
        id: 'education',
        name: 'Education',
        icon: 'school',
        color: '#10b981',
        count: grants.filter((g) => g.category === 'Education').length,
      },
      {
        id: 'agriculture',
        name: 'Agriculture',
        icon: 'leaf',
        color: '#84cc16',
        count: grants.filter((g) => g.category === 'Agriculture').length,
      },
      {
        id: 'women',
        name: 'Women',
        icon: 'woman',
        color: '#ec4899',
        count: grants.filter((g) => g.category === 'Women').length,
      },
      {
        id: 'innovation',
        name: 'Innovation',
        icon: 'bulb-outline',
        color: '#f59e0b',
        count: grants.filter((g) => g.category === 'Innovation').length,
      },
      {
        id: 'social-impact',
        name: 'Social Impact',
        icon: 'heart-outline',
        color: '#ef4444',
        count: grants.filter((g) => g.category === 'Social Impact').length,
      },
    ],
    [grants]
  );
   return { grants, categories };
};